[aws]
symbol = " "

[cmd_duration]
min_time = 1_000
show_milliseconds = true

[directory]
truncation_length = 8

[docker_context]
symbol = " "

[gcloud]
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[kubernetes]
disabled = false
symbol = "☸ "

[shell]
disabled = false
fish_indicator = '󰈺 '
