[directory]
truncation_length = 8

[kubernetes]
disabled = false
symbol = "ﴱ "

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[docker]
symbol = " "

[gcloud]
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
