name: aqua

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v2.11.0
